### ISSUE TITLE
Check failed: data.time > std::prev(trajectory.end())->first

### ISSUE THREAD

**Issue by JanezCim** [JanezCim/MRNTC#1]
When running cartographer with gazebo with turtlebot

**Comment by JanezCim** [comment]
Solved -> set use_sim_time to false
https://github.com/googlecartographer/cartographer_ros/issues/871

**Comment by harshad1600** [comment]
> Check failed: data.time > ##std::prev(trajectory.end())->first
the issue still exists for me even after setting parameter value to false

**Comment by harshad1600** [comment]
`Check failed: data.time > ##std::prev(trajectory.end())->first`
@JanezCim  the issue still exists for me even after setting sim_time to false.
Please help

**Comment by wjjjjyourFA** [comment]
It just hides the problem and doesn't solve it.
puzzled.
